places = {
    'RU': {
        'bus_station': 'автобусная остановка',
        'car_wash': 'автомойка',
        'pharmacy': 'аптека',
        'airport': 'аэропорт',
        'bank': 'банк',
        'atm': 'банкомат',
        'bar': 'бар',
        'gas_station': 'бензоколонка',
        'bowling_alley': 'боулинг',
        'veterinary_care': 'ветеринарная клиника',
        'art_gallery': 'галерея искусств',
        'gym': 'гимнастический зал',
        'casino': 'казино',
        'cafe': 'кафе',
        'movie_theater': 'кинотеатр',
        'museum': 'музей',
        'night_club': 'ночной клуб',
        'hair_care': 'парикмахерская',
        'amusement_park': 'парк развлечений',
        'park': 'парк',
        'bakery': 'пекарня',
        'car_repair': 'ремонт машин',
        'restaurant': 'ресторан',
        'beauty_salon': 'салон красоты',
        'subway_station': 'станция метро',
        'parking': 'стоянка',
    },
    'EN': {
        'airport': 'airport',
        'amusement_park': 'amusement park',
        'art_gallery': 'art gallery',
        'atm': 'atm',
        'bakery': 'bakery',
        'bank': 'bank',
        'bar': 'bar',
        'beauty_salon': 'beauty_salon',
        'bowling_alley': 'bowling_alley',
        'bus_station': 'bus_station',
        'cafe': 'cafe',
        'car_repair': 'car_repair',
        'car_wash': 'car_wash',
        'casino': 'casino',
        'gas_station': 'gas_station',
        'gym': 'gym',
        'hair_care': 'hair_care',
        'movie_theater': 'movie_theater',
        'museum': 'museum',
        'night_club': 'night_club',
        'park': 'park',
        'parking': 'parking',
        'pharmacy': 'pharmacy',
        'restaurant': 'restaurant',
        'subway_station': 'subway_station',
        'veterinary_care': 'veterinary_care',
    }
}
